kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "todo-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        // path of the template to use
        node('maven'){ 
        stage '1: Build the applications in the Dev Environment'
        openshiftBuild(namespace: 'shehzad-todo-app', buildConfig: 'todo-service-api', showBuildLogs: 'true')
        }
      type: JenkinsPipeline